@base_url = http://localhost:8088

###
GET {{base_url}}/rutas/list

###
GET {{base_url}}/rutas/list/1

###
GET {{base_url}}/rutas/view/1

###
GET {{base_url}}/rutas/list/-1

###
GET {{base_url}}/rutas/view/-1

###
POST {{base_url}}/rutas
Content-Type: application/json

{
    "longitud": 69,
    "dano": 69
}

###
GET {{base_url}}/rutas/view/1552

###
PUT {{base_url}}/rutas
Content-Type: application/json

{
    "id": 1552,
    "longitud": 2,
    "dano": 69
}

###
DELETE {{base_url}}/rutas/12